using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SharedDataGenerator;

[Generator]
public class SharedDataGenerator : ISourceGenerator {
    public void Initialize(GeneratorInitializationContext context) { }

    private static readonly DiagnosticDescriptor ResourceError = new(
        id: "RPG001",
        title: "Invalid SharedData Type",
        messageFormat: "The type '{0}' must derive from Godot.Resource",
        category: "Usage",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Execute(GeneratorExecutionContext context) {
        // Find all classes with the attribute
        IEnumerable<ClassDeclarationSyntax> classDeclarations = context.Compilation.SyntaxTrees
            .SelectMany(st => st.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>());

        foreach (ClassDeclarationSyntax? classDecl in classDeclarations) {
            SemanticModel model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            ISymbol? symbol = model.GetDeclaredSymbol(classDecl);

            AttributeData? attribute = symbol?.GetAttributes()
                .FirstOrDefault(ad => ad.AttributeClass?.Name == "SharedDataAttribute");

            // Extract the Type from the attribute argument
            if (attribute?.ConstructorArguments[0].Value is not ITypeSymbol typeSymbol) continue;

            var inheritsFromResource = false;
            ITypeSymbol? currentBase = typeSymbol;
            while (currentBase != null) {
                if (currentBase.ToDisplayString() == "Godot.Resource") {
                    inheritsFromResource = true;
                    break;
                }

                currentBase = currentBase.BaseType;
            }

            if (!inheritsFromResource) {
                Location? location = attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation();
                context.ReportDiagnostic(Diagnostic.Create(ResourceError, location, typeSymbol.Name));
                continue;
            }

            var sharedDataTypeName = typeSymbol.Name;
            var sharedDataTypeFullName = typeSymbol.ToDisplayString();

            var namespaceName = symbol?.ContainingNamespace.ToDisplayString();
            var className = symbol?.Name;

            var source =
                $$"""
                  // <auto-generated/>
                  using Godot;
                  using Godot.Collections;

                  namespace {{namespaceName}};

                  public partial class {{className}} {
                      public {{sharedDataTypeFullName}} {{sharedDataTypeName}} { 
                          set {
                              if (field is not null) return;
                              field = value;
                          } 
                          get {
                              if (field is null) field = new();
                              return field;
                          } 
                      }

                      protected override void _RegisterGeneratedProperties(Array<Dictionary> properties) {
                          properties.Add(new Dictionary {
                              ["name"] = nameof({{sharedDataTypeName}}),
                              ["type"] = (long)Variant.Type.Object,
                              ["hint"] = (long)PropertyHint.ResourceType,
                              ["hint_string"] = "{{sharedDataTypeName}}",
                              ["usage"] = (long)PropertyUsageFlags.Default | (long)PropertyUsageFlags.NeverDuplicate
                          });
                          base._RegisterGeneratedProperties(properties);
                      }

                      protected override bool _TryGetGeneratedProperty(StringName property, out Variant value) {
                          if (property == nameof({{sharedDataTypeName}})) {
                              value = Variant.From({{sharedDataTypeName}});
                              return true;
                          }
                          return base._TryGetGeneratedProperty(property, out value);
                      }

                      protected override bool _TrySetGeneratedProperty(StringName property, Variant value) {
                          if (property == nameof({{sharedDataTypeName}})) {
                              {{sharedDataTypeName}} = value.As<{{sharedDataTypeName}}>();
                              return true;
                          }
                          return base._TrySetGeneratedProperty(property, value);
                      }
                  }
                  """;
            context.AddSource($"{className}_SharedData.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }
}